name: Build LLVM XCFrameworks for Testing
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build-llvm:
    runs-on: macos-latest
    strategy:
      matrix:
        platformArch: [iphoneos]
    timeout-minutes: 1200
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - run: curl -OL https://github.com/light-tech/LLVM-On-iOS/releases/download/llvm15.0.3/tools.tar.xz && tar xzf tools.tar.xz
      - name: Build LLVM for ${{ matrix.platformArch }}
        run: |
          echo "Python is at $(which python)"
          export PATH=$PATH:`pwd`/tools/bin
          source build-llvm.sh && build_llvm ${{ matrix.platformArch }}
      - run: tar -cJf LLVM-${{ matrix.platformArch }}.tar.xz LLVM-${{ matrix.platformArch }}/
      - uses: actions/upload-artifact@v3
        with:
          name: LLVM-${{ matrix.platformArch }}
          path: LLVM-${{ matrix.platformArch }}.tar.xz

  create-xcframework:
    needs: build-llvm
    runs-on: macos-latest
    if: ${{ false }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - name: Extract artifacts
        run: find . -name "*.tar.xz" -exec tar xzf {} \;

      - name: Create XCFramework for Intel Macs
        run: source build-llvm.sh && create_xcframework iphoneos iphonesimulator maccatalyst
      - run: tar -cJf LLVM_Intel.xcframework.tar.xz LLVM.xcframework
      - uses: actions/upload-artifact@v3
        with:
          name: LLVM_Intel
          path: LLVM_Intel.xcframework.tar.xz

      - uses: actions/upload-artifact@v3
        with:
          name: libclang
          path: libclang.tar.xz

      - name: Create XCFramework for M1 Macs
        run: source build-llvm.sh && rm -rf LLVM.xcframework && create_xcframework iphoneos iphonesimulator-arm64 maccatalyst-arm64
      - run: tar -cJf LLVM_M1.xcframework.tar.xz LLVM.xcframework
      - uses: actions/upload-artifact@v3
        with:
          name: LLVM_M1
          path: LLVM_M1.xcframework.tar.xz
